version: "3.9"

services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432

  bot:
    build:
      context: .
    depends_on:
      - postgres
    restart: unless-stopped
    expose:
      - 8080
    entrypoint: ["/bin/sh", "entrypoint.sh"]

volumes:
  postgres_data:
